### ISSUE TITLE
gtburst alloc issue

### ISSUE THREAD

**Issue by ghost** [fermi-lat/pyBurstAnalysisGUI#2]
When loading gtburst after `$ source $FERMI_DIR/fermi-init.sh` the following error occurs

`Loading pyBurstAnalysisGUI v. 02-02-00p0 ....... done`
`alloc: invalid block: 0x252e030: 0 0`

I've tried it on Ubuntu 16.04 and now on Fedora24 with the pre-compiled binaries but they end up with the same error.

My `$ echo $FERMI_DIR$` output is

`/home/syeda/ScienceTools-v11r5p3-fssc-20180124-x86_64-unknown-linux-gnu-libc2.23/x86_64-unknown-linux-gnu-libc2.23/`

**Comment by donhorner** [comment]
Sorry no one got back to you sooner, but we don't really support ScienceTools v11r5p3 anymore.  We've moved on to using conda to distribute the analysis tools and rebranded them as the Fermitools.  Assuming you haven't already done so, can you [install the Fermitools](https://github.com/fermi-lat/Fermitools-conda/wiki/Installation-Instructions) and see if you still have trouble with gtburst?
