### ISSUE TITLE
missing templates in Conda install. 

### ISSUE THREAD

**Issue by grburgess** [fermi-lat/pyBurstAnalysisGUI#4]
Hello,

I was running gtGurst via the command line and it seems some templates are missing or the IRF definitions need to be updated. I have run the GtBurst updater. 

Here is the output:

```
I was looking for template_4years_P8_V2_scaled.fits,gll_iem_v06.fits into /opt/conda/envs/threeML_env/share/fermitools/refdata/fermi/galdiffuse

...


File "/opt/conda/envs/threeML_env/lib/python2.7/site-packages/fermitools/GtBurst/LikelihoodComponent.py", line 41, in findGalacticTemplate
    irfname))

GtBurst.GtBurstException.GtBurstException: You don't have a Galactic template for IRF P8R3_TRANSIENT020E_V2. Cannot continue.
```

looking in that folder, I only see gll_iem_**v07.**fits which might be the issue. Thanks!

**Comment by omodei** [comment]
I have fixed this (it now looks for gll_iem_v07.fits).

**Comment by omodei** [comment]
To update to the latest version, simply execute this command:
python ${CONDA_PREFIX}/lib/python2.7/site-packages/fermitools/GtBurst/updater.py

**Comment by grburgess** [comment]
Hello. Thanks @omodei! I confirm that this is not working in my latest conda install.
